service: sdg-authenticate-api

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  profile: serverless
  environment:
    PLAYERS_LAMBDA_FN_NAME: sdg-players-api-${opt:stage, self:provider.stage}-get
    PLAYERS_LAMBDA_FN_REGION: ${self:provider.region}
  deploymentBucket: 
    name: com.sunday-disc-golf-api.${self:provider.region}.deploys
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "arn:aws:lambda:${opt:region, self:provider.region}:*:function:${self:provider.environment.PLAYERS_LAMBDA_FN_NAME}"

functions:
  authenticate-player:
    handler: player.player
    events:
      - http:
          path: authenticate/player
          method: post
          cors: true 
